// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahsNq2To6hgqc6b2CeIqNrM7f778jknc',
    appId: '1:389470171647:web:c85dc71703cec41b22f7ca',
    messagingSenderId: '389470171647',
    projectId: 'webtnmfact',
    authDomain: 'webtnmfact.firebaseapp.com',
    storageBucket: 'webtnmfact.firebasestorage.app',
    measurementId: 'G-L2C1WG9GJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDJXFFOWwtf1SMUBNqjVRqHXHbSMrMovg',
    appId: '1:389470171647:android:fa32951215edd9e322f7ca',
    messagingSenderId: '389470171647',
    projectId: 'webtnmfact',
    storageBucket: 'webtnmfact.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNsPR_obbR14mwfkW6csN85w-yjVFoM4',
    appId: '1:389470171647:ios:8e929731e66f978122f7ca',
    messagingSenderId: '389470171647',
    projectId: 'webtnmfact',
    storageBucket: 'webtnmfact.firebasestorage.app',
    iosBundleId: 'com.example.tnmFact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTNsPR_obbR14mwfkW6csN85w-yjVFoM4',
    appId: '1:389470171647:ios:8e929731e66f978122f7ca',
    messagingSenderId: '389470171647',
    projectId: 'webtnmfact',
    storageBucket: 'webtnmfact.firebasestorage.app',
    iosBundleId: 'com.example.tnmFact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBahsNq2To6hgqc6b2CeIqNrM7f778jknc',
    appId: '1:389470171647:web:01ec2b8f273d808022f7ca',
    messagingSenderId: '389470171647',
    projectId: 'webtnmfact',
    authDomain: 'webtnmfact.firebaseapp.com',
    storageBucket: 'webtnmfact.firebasestorage.app',
    measurementId: 'G-BXY3V1WW8Z',
  );

}